server.port: 8085

spring:
  mvc.path match:
    matching-strategy: ant-path-matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cze06skkkryn.sa-east-1.rds.amazonaws.com:3306/aula
    username: admin
    password: Pass2020
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false

  cloud:
    aws:
      sqs:
        queue-url: https://sqs.sa-east-1.amazonaws.com/174457625138/fileira